version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps):"
    automerge:
      enabled: true
      options:
        merge_method: "squash" # Specify the desired merge method ("merge", "squash", or "rebase")
        merge_filter:
          branches:
            - "develop"
