name: Build on PR
on:
  pull_request:
    types:
      - closed
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      # Add your build and test steps here
      - name: Compile C++ code
        run: |
          yarn
          yarn run compile

      - name: Test C++ code
        run: |
          yarn run exec
